title: Frank's Homepage
page-top-title: Frank
top-section-bg-text: The best throw of the dice is to throw them away
home-subtitle: Frank&ensp;|&ensp;Qinchen Wu
copyright-text: '&copy; Qinchen Wu 2023-2025. All Rights Reserved.'
